### ISSUE TITLE
Unknown Region Error for some country codes

### ISSUE THREAD

**Issue by onomated** [holidays/holidays#195] opened 2016-06-03 16:39 UTC
Recently updated to v4.1 of this gem and getting UnknownRegionError for `be`, `bg`. 

Usage: 
```
::Holidays.between(Date.civil(2016, 1, 1), Date.civil(2016, 12, 31), :bg)
```
The generated regions for these countries do not include the two letter country codes, even though the region modules include the two letter country codes as `defined_regions`.  

These worked in v3 of the gem.

**Comment by ptrimble** [comment] 2016-06-03 23:33
Thank you for the report! I really appreciate it, especially since you definitely found regressions. 😨 

I know what is causing the problem with `:be`. There was a previous pr/issue that wanted the gem to allow for french or dutch language options for languages for `:be`. We do not have internationalization yet and so the temporary solution was to split them into `:be_fr` and `:be_nl`. 

I understand that this isn't the best solution but I have plans to work on refactoring the holiday definitions to allow for different names based on a passed-in language. This would consolidate to a common region but still allow for you to see your desired language.

In addition, I accidentally left `lib/generated_definitions/be.rb` in the current version. However, since `:be` is not actually in the `lib/generated_definitions/REGIONS.rb` it won't be available. That file should really be removed with my current implementation. That's a mistake on my part. Sorry. 😦 

As for `:bg` we seem to be in a similar boat. From what I can gather this is a regression I introduced with the v4 upgrade and we just don't have any specific tests to cover it (which is frustrating). The `lib/generated_definitions/bg.rb` file has `:bg_en` and `:bg_bg` regions defined, but with the new way I am doing things this means that `:bg` itself won't be considered a 'region'.

So what makes the most sense for you? There are multiple ways I can handle this:

* gem does not change and you change to use the specific region+language you need. I would then prioritize the refactor for the language stuff to 'solve' the problem. No ETA on that. 😦 
* I can make some combination of changes to restore some of the previous behavior (while adding tests so this is caught automatically in the future). I could have `:be` and `:bg` default to one language or the other.
* Some other solution that I missed

Thoughts?

**Comment by onomated** [comment] 2016-06-04 00:14
Thanks for the detailed analysis @ptrimble.  It was a simple change for me to specify the region+language and keep the gem as is.  So I'm good with the first option.  Only problem with that is other users of the gem may run into the same issue and spend time digging around to figure out what's wrong, so defaulting to one language can save time for other users, or just documenting this may suffice.  

+1 for supporting localization in the future.  That'll be awesome.  I've done some localization of the holidays with some convoluted pattern matching on names and dates against translations in [Jollyday](https://github.com/svendiedrichsen/jollyday), it'll be awesome if that was just built in.

Cheers on a fantastic gem!

**Comment by ptrimble** [comment] 2016-06-04 23:15
Great, thanks! I'm going to close this issue and open a new one that details exactly what I want to do with the localization. Thanks again for the report, feel free to hit me up again if you run into any other issues.

**Closed by ptrimble** 2016-06-04 23:15 UTC
Labels: bug
